In [1]:
%pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/98/d7/1cc7a11118408ad21a5379ff2a4e0b0e27504c68ef6e808ebaa90ee95902/numpy-1.26.0-cp312-cp312-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.1 kB ? eta -:--:--
     --------------------------------- ------ 51.2/61.1 kB ? eta -:--:--
     -------------------------------------- 61.1/61.1 kB 820.0 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.5 MB 279.3 kB/s eta 0:00:56
   ---------------------------------------- 0.0/15.5 MB 279.3 kB/s eta 0:00:56
   ---------------------------------------- 0.1/15.5 MB 301.2 kB/s eta 0:00:52
   ---------------------------------------- 0.1/15.5 

Numpy Basics

In [5]:
import numpy as np

List and Array

In [2]:
l = [2, 1, 5, 8]
print(type(l))

<class 'list'>


In [6]:
arr = np.array(l)
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
a = np.array([2, 5, 8])
b = np.array([[4, 2, 1], [4, 6, 9]])

In [9]:
a.ndim, b.ndim

(1, 2)

In [13]:
b.shape, a.shape

((2, 3), (3,))

In [14]:
b.size, a.size

(6, 3)

In [15]:
a.dtype, b.dtype

(dtype('int32'), dtype('int32'))

In [19]:
np.zeros([4, 4], dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [20]:
np.ones([2, 3], dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

Reshape and Random Number Generator

In [21]:
np.random.random(3)

array([0.22346591, 0.25593586, 0.46219242])

In [26]:
d = np.arange(4)
d

array([0, 1, 2, 3])

In [27]:
d.reshape(2, 2)

array([[0, 1],
       [2, 3]])

In [29]:
np.linspace(2, 5, 10)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

Arithmetic Operations on Array

In [31]:
a = np.array([3, 2, 7, 0])
b = np.array([4, 2, 8, 1])

In [32]:
add_arr = a+b
add_arr

array([ 7,  4, 15,  1])

In [33]:
np.add(a, b)

array([ 7,  4, 15,  1])

In [34]:
sub_arr = a-b
sub_arr

array([-1,  0, -1, -1])

In [35]:
np.subtract(a, b)

array([-1,  0, -1, -1])

In [36]:
multiply_arr = a*b
multiply_arr

array([12,  4, 56,  0])

In [37]:
np.multiply(a, b)

array([12,  4, 56,  0])

In [38]:
divide_arr = a/b
divide_arr

array([0.75 , 1.   , 0.875, 0.   ])

In [39]:
np.divide(a, b)

array([0.75 , 1.   , 0.875, 0.   ])

In [40]:
arr = np.max(a), np.min(b)
arr

(7, 1)

Now, if we want to find the maximum or minimum from the rows or the columns then we have to add 0 or 1. See how it works: 

In [42]:
arr = np.array([[3, 2, 8],
         [5, 0, 8],
         [23, 89, 8]])
arr

array([[ 3,  2,  8],
       [ 5,  0,  8],
       [23, 89,  8]])

In [43]:
max_col_element = np.max(arr, 0)
min_row_element = np.min(arr, 1)

In [44]:
print("Max element on the columns is: ", max_col_element)
print("Minimun elemnt on the rows is: ", min_row_element)

Max element on the columns is:  [23 89  8]
Minimun elemnt on the rows is:  [2 0 8]


Array Sorting

In [46]:
arr = np.array([
    [3, 2, 7],
    [86, 4, 20],
    [2, 12, 4]
])
arr

array([[ 3,  2,  7],
       [86,  4, 20],
       [ 2, 12,  4]])

Sorted of the column axis

In [47]:
arr1 = np.sort(arr, 0)
arr1

array([[ 2,  2,  4],
       [ 3,  4,  7],
       [86, 12, 20]])

Sorted on the row axis

In [49]:
arr2 = np.sort(arr, 1)
arr2

array([[ 2,  3,  7],
       [ 4, 20, 86],
       [ 2,  4, 12]])

Sorted on no axis

In [51]:
arr3 = np.sort(arr, axis=None)
arr3

array([ 2,  2,  3,  4,  4,  7, 12, 20, 86])

We can choose which type of sorting we want perform using the kind parameter inside the sort function. We can either choose between quicksort, mergesort and heapsort.

In [52]:
arr4 = np.sort(arr, axis=None, kind='mergesort')
arr4

array([ 2,  2,  3,  4,  4,  7, 12, 20, 86])

Array Merging

In [53]:
first = np.array([3, 9, 5])
second = np.array([43, 2, 6])

In [54]:
np.vstack((first, second))

array([[ 3,  9,  5],
       [43,  2,  6]])

In [55]:
np.hstack((first, second))

array([ 3,  9,  5, 43,  2,  6])

In [56]:
third = np.array([[2, 4], [6, 8]])
fourth = np.array([[3, 5], [7, 9]])

In [57]:
np.concatenate((third, fourth), axis=0)

array([[2, 4],
       [6, 8],
       [3, 5],
       [7, 9]])

In [58]:
np.concatenate((third, fourth), axis=1)

array([[2, 4, 3, 5],
       [6, 8, 7, 9]])

In [63]:
arr = np.arange(9.0).reshape(3, 3)
arr

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [65]:
new_arr = np.vsplit(arr, 1)
new_arr

[array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])]

In [70]:
new_arr2 = np.hsplit(arr, 1)
new_arr2

[array([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])]