In [18]:
import numpy as np

## DataTypes & Attributes 

In [28]:
# numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [20]:
type(a1)

numpy.ndarray

In [29]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [30]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [32]:
a1.shape

(3,)

In [33]:
a2.shape

(2, 3)

In [34]:
a3.shape

(2, 3, 3)

In [35]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [36]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [37]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [39]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [41]:
# Create a DataFrame from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [42]:
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [43]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
ones.dtype

dtype('float64')

In [45]:
type(ones)

numpy.ndarray

In [46]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
range_array = np.arange(0, 5, 0.5)
range_array

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [48]:
random_array = np.random.randint(0, 10, size=(5, 4))
random_array

array([[2, 0, 7, 7],
       [1, 5, 7, 7],
       [5, 4, 1, 1],
       [6, 1, 8, 5],
       [1, 3, 9, 8]])

In [50]:
random_array_2 = np.random.random((4, 3))
random_array_2

array([[0.90910884, 0.81890184, 0.44068398],
       [0.12336053, 0.69000509, 0.58226427],
       [0.97290399, 0.67904942, 0.45087873],
       [0.57766231, 0.66433012, 0.23877007]])

In [51]:
random_array_2.shape

(4, 3)

In [52]:
random_array_2.size

12

In [54]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.2148466 , 0.2279352 , 0.96596598],
       [0.35336833, 0.80335661, 0.38982337],
       [0.51575361, 0.46157438, 0.98507557],
       [0.921298  , 0.42239988, 0.61147279],
       [0.87184106, 0.4858286 , 0.87541573]])

In [ ]:
# Pseudo-random numbers
np.random.seed()