In [18]:
import numpy as np

## 1. DataTypes & Attributes 

In [28]:
# numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [20]:
type(a1)

numpy.ndarray

In [29]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [30]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [32]:
a1.shape

(3,)

In [33]:
a2.shape

(2, 3)

In [34]:
a3.shape

(2, 3, 3)

In [35]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [36]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [37]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [39]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [41]:
# Create a DataFrame from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [42]:
simple_array = np.array([1, 2, 3])
simple_array

array([1, 2, 3])

In [43]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
ones.dtype

dtype('float64')

In [45]:
type(ones)

numpy.ndarray

In [46]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
range_array = np.arange(0, 5, 0.5)
range_array

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [48]:
random_array = np.random.randint(0, 10, size=(5, 4))
random_array

array([[2, 0, 7, 7],
       [1, 5, 7, 7],
       [5, 4, 1, 1],
       [6, 1, 8, 5],
       [1, 3, 9, 8]])

In [50]:
random_array_2 = np.random.random((4, 3))
random_array_2

array([[0.90910884, 0.81890184, 0.44068398],
       [0.12336053, 0.69000509, 0.58226427],
       [0.97290399, 0.67904942, 0.45087873],
       [0.57766231, 0.66433012, 0.23877007]])

In [51]:
random_array_2.shape

(4, 3)

In [52]:
random_array_2.size

12

In [64]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675],
       [0.87001215, 0.97861834, 0.79915856],
       [0.46147936, 0.78052918, 0.11827443]])

In [70]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(0, 10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [73]:
np.random.seed(3)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ],
       [0.44080984, 0.02987621, 0.45683322],
       [0.64914405, 0.27848728, 0.6762549 ]])

In [75]:
random_array_5

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ],
       [0.44080984, 0.02987621, 0.45683322],
       [0.64914405, 0.27848728, 0.6762549 ]])

## 3. Viewing arrays & matrices

In [76]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [77]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a1

array([1, 2, 3])

In [79]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [80]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [81]:
a1[0]

1

In [82]:
a2[0]

array([1. , 2. , 3.3])

In [83]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
a3[0][1][1]

5

In [85]:
a3[1][:2]

array([[10, 11, 12],
       [13, 14, 15]])

## 4. Manipulating & Comparing arrays

## Arithmetic

In [86]:
a1

array([1, 2, 3])

In [87]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [95]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [96]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [102]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [100]:
reshaped_array = a2[:, :, np.newaxis]
reshaped_array

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [101]:
results = a3 * reshaped_array
results

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [103]:
a1 / a2

array([[1.        , 1.        , 0.90909091],
       [0.25      , 0.4       , 0.46153846]])

In [104]:
a1 // a2

array([[1., 1., 0.],
       [0., 0., 0.]])

In [105]:
np.add(a1, a2)

array([[2. , 4. , 6.3],
       [5. , 7. , 9.5]])

In [106]:
np.divide(a1, a2)

array([[1.        , 1.        , 0.90909091],
       [0.25      , 0.4       , 0.46153846]])

In [107]:
a1 % ones

array([[0., 0., 0.],
       [0., 0., 0.]])

In [108]:
np.mod(a1 , ones)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [112]:
a1 ** 3

array([ 1,  8, 27], dtype=int32)

In [110]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [113]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

## Aggregation